# Generated by Django 2.0.4 on 2018-05-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSiteTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_site', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('sim', models.CharField(max_length=50)),
                ('disp_type', models.CharField(max_length=50)),
                ('disp_size', models.CharField(max_length=50)),
                ('disp_resolution', models.CharField(max_length=50)),
                ('disp_multitouch', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=25)),
                ('chipset', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('card_slot', models.CharField(max_length=50)),
                ('internal_memory', models.CharField(max_length=50)),
                ('wlan', models.CharField(max_length=50)),
                ('bluetooth', models.CharField(max_length=50)),
                ('usb', models.CharField(max_length=80)),
                ('battery', models.CharField(max_length=50)),
                ('colors', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('p_image', models.FileField(upload_to='')),
                ('shop_link', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductsTesting')),
            ],
        ),
        migrations.AddField(
            model_name='productsitetesting',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductsTesting'),
        ),
    ]
