# Generated by Django 2.0.4 on 2018-05-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testuser_testuserinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
