# Generated by Django 2.0.4 on 2018-05-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180507_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImagesTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image1', models.TextField()),
                ('p_image2', models.TextField()),
                ('p_image3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductSiteTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_site', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=50)),
                ('p_net', models.CharField(max_length=50)),
                ('p_launch', models.CharField(max_length=50)),
                ('p_body', models.CharField(max_length=50)),
                ('p_display', models.CharField(max_length=50)),
                ('p_platf', models.CharField(max_length=50)),
                ('p_memory', models.CharField(max_length=50)),
                ('p_camera', models.CharField(max_length=50)),
                ('p_sound', models.CharField(max_length=50)),
                ('p_comms', models.CharField(max_length=50)),
                ('p_features', models.TextField()),
                ('p_battery', models.CharField(max_length=50)),
                ('p_misc', models.CharField(max_length=50)),
                ('p_amount', models.CharField(max_length=50)),
                ('p_category', models.TextField()),
                ('p_bname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('rating', models.FloatField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductsTesting')),
            ],
        ),
        migrations.RemoveField(
            model_name='testuserinfo',
            name='the_user',
        ),
        migrations.DeleteModel(
            name='TestUser',
        ),
        migrations.DeleteModel(
            name='TestUserInfo',
        ),
        migrations.AddField(
            model_name='productsitetesting',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductsTesting'),
        ),
        migrations.AddField(
            model_name='productimagestesting',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductsTesting'),
        ),
    ]
